### ISSUE TITLE
Python indentation

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/.vim#12]
so say my cursor is on the `p` of `pass`:

```
def get_ethereum_address():
    |p|ass
```

Currently, if I hit `o` it will place the cursor:

```
def get_ethereum_address():
    pass
    ||
```

But I'd like it to be placed indented since `pass` is an ending keyword:

```
def get_ethereum_address():
    pass
||
```

**Comment by riverallzero** [comment]
I think because it's in a define function, | | locations looks like it's in the tap pressed position..

**Comment by Jaymon** [comment]
```python
if ch| |in set(["#"]):
    break
```

Cursor is between `ch` and `in`, I hit `o`:

```python
if ch in "#":
| |
    break
```

It seems to be something with the `#` and, I guess, how comments affect the indent.

**Comment by Jaymon** [comment]
When I hit `O` (shift-o) then indentation for edit should be set to the line I was on when I hit `O`

**Comment by Jaymon** [comment]
```python
if True:
    if True:
        pass

    elif True:
        pass

elif True|
```

So the cursor is right after the `e` in that last `elif True` when I type `:`  it will reformat to this:

```python
if True:
    if True:
        pass

    elif True:
        pass

    elif True:|
```

It does this with `else` also. I'd like to take a look at the rule set and see if I can check if my `elif` or `else` is aligned with an appropriate statement and ignore trying to indent if it is. So basically, it would check the current indentation, in this case the current indentation would be 0, then it would check the previous statement at 0, if that statement is `if` or `elif` then it will just return 0 instead of checking the previous statement, seeing it is `elif` at indent 4 and return 4 instead.
